pipeline{
    agent {
        label 'Dev'
    }
    stages{
        stage("Build"){
            steps{
                echo 'echo"am building image in docker" '
            }
        }
        stage("Test"){
            steps{
                echo 'echo"am testing image in docker" '
            }
        }
        stage("deploy"){
            steps{
                echo 'echo"I am deploying image in kubernetes" '
            }
        }
        stage("cpudetails"){
            steps{
                echo 'echo"cpudetails" '
            }
        }
    }
}

    